export const evolution = [
  {
    name: "Fan Tan",
    gameid: "5cb6aa4e2ce1c775c568561401ffdfca",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Fan Tan.png",
  },
  {
    name: "Speed Roulette",
    gameid: "b4af506243cafae52908e8fa266f8ff6",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Speed Roulette.png",
  },
  {
    name: "Infinite Blackjack",
    gameid: "58d7089aa20bce7f70e0e2ce81e888f4",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Infinite Blackjack.png",
  },
  {
    name: "Craps",
    gameid: "689dd8e8f17dae910dba9fdd4990d41e",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Craps.png",
  },
  {
    name: "First Person Dream Catcher",
    gameid: "7ee0da50996278d7fe5136f86f368fa5",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Dream Catcher.png",
  },
  {
    name: "First Person Dragon Tiger",
    gameid: "4b4c45709dfd8188d7d6d12fae15bd42",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Dragon Tiger.png",
  },
  {
    name: "First Person Mega Ball",
    gameid: "3150b1cd8fbbddd94d36f20fab504653",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Mega Ball.png",
  },
  {
    name: "First Person Lightning Baccarat",
    gameid: "fec1b730e804bf14bd471a1e9b82bf44",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Lightning Baccarat.png",
  },
  {
    name: "First Person Craps",
    gameid: "823245918aa2afd108a5912e363c083c",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Craps.png",
  },
  {
    name: "First Person Baccarat",
    gameid: "e18dfa4a5dd4a0f2d8b45337bd6abb9d",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Baccarat.png",
  },
  {
    name: "First Person Golden Wealth Baccarat",
    gameid: "88e49e3fb9a9883f01f167d03f5efdcb",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Golden Wealth Baccarat.png",
  },
  {
    name: "First Person American Roulette",
    gameid: "88b2d98462fbc45d6d31e95083e183df",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person American Roulette.png",
  },
  {
    name: "First Person Deal or No Deal",
    gameid: "c715eb06391fabe5275d0b56440f49f3",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Deal or No Deal.png",
  },
  {
    name: "First Person Blackjack",
    gameid: "4ac0e874a4d5fc55bcdba5302b43bc96",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Blackjack.png",
  },
  {
    name: "First Person Lightning Blackjack",
    gameid: "74914b065a9e6b9c7cb8a0e4b17294ed",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Lightning Blackjack.png",
  },
  {
    name: "First Person Roulette",
    gameid: "a82670530f49a6b3445dc1a592a2eb9e",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Roulette.png",
  },
  {
    name: "Dream Catcher",
    gameid: "7f50a6fbfcd9257299303b5757d43525",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Dream Catcher.png",
  },
  {
    name: "Football Studio Dice",
    gameid: "1909b4e3380dc37654f8e3997e63ec1b",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Football Studio Dice.png",
  },
  {
    name: "Dead or Alive: Saloon",
    gameid: "eda1a2c5edb8370f8df58dcf8e1381b9",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Dead or Alive: Saloon.png",
  },
  {
    name: "First Person Lightning Roulette",
    gameid: "f5ee6fce16d369d1a656f3b227fc7236",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/First Person Lightning Roulette.png",
  },
  {
    name: "Football Studio",
    gameid: "392e13e38b3cec5ad259254a206d343a",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Football Studio.png",
  },
  {
    name: "Teen Patti",
    gameid: "0617a82334f4f1766cf282ce906e1df7",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Teen Patti.png",
  },
  {
    name: "Super Andar Bahar",
    gameid: "f7b98e899461bdd49f92afc36b4c0db5",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Super Andar Bahar.png",
  },
  {
    name: "Crazy Time",
    gameid: "917c0c51d248c33eb058e3210a2e7371",
    type: "CasinoLive",
    icon: "https://huidu-bucket.s3.ap-southeast-1.amazonaws.com/api/evoplay/Crazy Time.png",
  },
];
